name: Analyze

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v1
      - name: Use Node 12.16.2
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - name: Install NPM Packages
        run: npm ci
      - name: Lint
        run: npm run lint

  bundlewatch:
    runs-on: ubuntu-latest
    name: Bundlewatch
    steps:
      - uses: actions/checkout@v1
      - name: Use Node 12.16.2
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Bundle watch
        run: npm run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_TOKEN }}

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Use Node 12.16.2
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
