name: Build & Publish
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    name: 'Build & Test (${{ matrix.os }} - Node ${{ matrix.node-version }})'
    strategy:
      matrix:
        node-version: ['12.16.2']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM Packages
        run: npm ci
      - name: Lint extension
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test

  publish:
    name: Publish extension
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - name: Install NPM packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to GitHub pages
        run: echo TODO
