name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Create build archives
        id: archives
        run: |
          tag=${GITHUB_REF#refs/tags/}
          tar_archive="gr-20.$tag.tar.gz"
          zip_archive="gr-20.$tag.zip"
          tar -czf "$tar_archive" build/
          zip -r9 "$zip_archive" build/
          echo "::set-output name=tar_archive::$tar_archive"
          echo "::set-output name=zip_archive::$zip_archive"
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN_GITHUB }}
      - name: Upload release tar archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.archives.outputs.tar_archive }}
          asset_name: ${{ steps.archives.outputs.tar_archive }}
          asset_content_type: application/tar+gzip
      - name: Upload release zip archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.archives.outputs.zip_archive }}
          asset_name: ${{ steps.archives.outputs.zip_archive }}
          asset_content_type: application/zip
      - name: Publish to GitHub Pages
        run: |
          mv build .build
          tag=${GITHUB_REF#refs/tags/}
          git fetch
          git checkout gh-pages
          cp -r .build/* .
          rm -rf .build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Add build for version $tag"
          git push
