name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish extension
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Publish to GitHub pages
        run: echo TODO
